name: Docs deployment

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build

      - name: Set up python
        uses: actions/setup-python@v4
  
      - name: Install dependencies
        run: |
          pip install boto3
        shell: bash

      - name: run python s3 script
        run: python .github/workflows/scripts/main.py
        env:
          SOURCE-ROOT: "./build"
          STORAGE-ENDPOINT: ${{ vars.STORAGE_ENDPOINT }}
          STORAGE-REGION: ${{ vars.STORAGE_REGION }}
          STORAGE-BUCKET: ${{ vars.STORAGE_BUCKET }}
          STORAGE-ACCESS-KEY-ID: ${{ secrets.ACCESS_KEY_ID }}
          STORAGE-SECRET-ACCESS-KEY: ${{ secrets.SECRET_ACCESS_KEY }}
